services:
  database:
    image: mysql:8
    container_name: symfonyBlog
    ports:
      - '3306:3306'
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD


volumes:
  dev_mysql_data: